version: "3.0"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: "simple2_image"
    container_name: simple2
    restart: unless-stopped
    tty: true
    # environment:
    #   SERVICE_NAME: app
    #   SERVICE_TAGS: dev
    working_dir: /var/www/simple
    volumes:
        - ./:/var/www/simple
    networks:
        - esnet
    depends_on:
      - db
      - redis
      - elasticsearch

  webserver:
    image: "nginx:alpine"
    volumes:
        - "./nginx/:/etc/nginx/conf.d/"
        - "./:/var/www/simple"
    ports:
        - "8000:80"
        - "443:443"
    networks:
        - esnet
    depends_on:
      - elasticsearch
      - app
  db:
    image: "mysql:5.7"
    environment:
        - MYSQL_DATABASE=simple
        - MYSQL_ROOT_PASSWORD=digital123
    volumes:
        - dbdata:/var/lib/mysql
    ports:
        - "3306:3306"
    restart: unless-stopped
    networks:
        - esnet
    # depends_on:
    #  - app

  redis:
    image: "redis"
    networks: 
        - esnet
    ports:
        - "6379:6379"
    depends_on:
      - db

  elasticsearch:
    image: "elasticsearch:5.6"
    environment:
        - node.name=elasticsearch
        - discovery.seed_hosts=elasticsearch
        - cluster.initial_master_nodes=elasticsearch
        - cluster.name=elasticsearch
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
        - elasticsearchdata:/usr/share/elasticsearch/data
    ports:
        - "9200:9200"
    networks:
        - esnet
    depends_on:
      - redis

#Docker Volumes
volumes:
   dbdata:
   elasticsearchdata:

#Docker Networks
networks:
  esnet:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16